# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:year/:month/:day/:title 

exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
#exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md","*.sublime-project",".gitignore","Gemfile","Gemfile.lock"]

markdown: kramdown
highlighter: rouge

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#

title : Wyver Solutions Ltd
tagline: 'Independent learning technology consultants'
description: 'Independent learning technology consultants'
author :
  name : Mark Berthelemy
  email : mberthelemy@wyversolutions.co.uk
  github : username
  twitter : username
  feedburner : feedname

plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 12

paginate_path: "/blog/page:num/"

name: Wyver Solutions Ltd
url: https://www.wyversolutions.co.uk

collections_dir: my_collections

collections:
    people:
       output: true
       permalink: /people/:path/
    ufiwebinar:
       output: false
       permalink: /ufiwebinar/:path/

      
defaults:
  - scope:
      path: ""
      type: people
    values:
      layout: page 
